### ISSUE TITLE
DTool updated, Cowboy's buttons stopped working

### ISSUE THREAD

**Issue by esper** [przenz/CKEditor-Dtool-plugin#2]
Hi,
DTool is updated during this weekend with a new editor which e.g. contains format changers. But the change made the Cowboy's addons buttons ("Date and signum", "Verification template" and "Show/hide") stopped working.

BRs
Magnus

**Comment by przenz** [comment]
Hi Magnus,

I have disabled all Cowboy's Addons buttons since Greasmonkey won't see CKEDITOR instance properly. These buttons can be replaced with custom buttons plugin for CKeditor.
Changes are visible after updating user script in Greasmonkey.

Br, Mateusz
